ALTER TABLE unidades ADD COLUMN IF NOT EXISTS tipo VARCHAR(80) NULL;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS placas_2025 VARCHAR(20) NULL;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS resguardante_2 VARCHAR(150) NULL;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS rpe_resguardante VARCHAR(80) NULL;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS centro_gestor VARCHAR(80) NULL;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS centro_costos VARCHAR(80) NULL;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS ubicacion_tecnica VARCHAR(180) NULL;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS arrendadora VARCHAR(120) NULL;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS imagen_url TEXT NULL;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS historial_json JSON NULL;
ALTER TABLE departamentos ADD COLUMN IF NOT EXISTS orden INT NOT NULL DEFAULT 999;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS tipo_reporte VARCHAR(50) NULL;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS autor_nombre VARCHAR(150) NULL;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS autor_departamento VARCHAR(150) NULL;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS gravedad VARCHAR(30) NULL;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS detalle_siniestro VARCHAR(150) NULL;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS involucrados TEXT NULL;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS fecha_hechos DATE NULL;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS lugar_hechos VARCHAR(250) NULL;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS horario_hechos VARCHAR(100) NULL;
ALTER TABLE reportes ADD COLUMN IF NOT EXISTS pdf_url TEXT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS debe_cambiar_password TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS password_changed_at DATETIME NULL;
CREATE TABLE IF NOT EXISTS recuperacion_password (
  id VARCHAR(64) PRIMARY KEY, usuario_id INT NOT NULL, otp_hash VARCHAR(255) NOT NULL,
  medio VARCHAR(20) NOT NULL, expira_at DATETIME NOT NULL, usado TINYINT(1) NOT NULL DEFAULT 0,
  token_hash VARCHAR(255) NULL, token_expira_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS reporte_unidades (
  reporte_id INT NOT NULL, unidad_id INT NOT NULL, PRIMARY KEY (reporte_id, unidad_id),
  FOREIGN KEY (reporte_id) REFERENCES reportes(id) ON DELETE CASCADE,
  FOREIGN KEY (unidad_id) REFERENCES unidades(id)
);
CREATE TABLE IF NOT EXISTS reporte_seguimiento (
  id INT AUTO_INCREMENT PRIMARY KEY, reporte_id INT NOT NULL, usuario_id INT NOT NULL,
  mensaje TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (reporte_id) REFERENCES reportes(id) ON DELETE CASCADE,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE TABLE IF NOT EXISTS cargas_edenred (
  id VARCHAR(64) PRIMARY KEY, periodo_json JSON NOT NULL, transacciones_json JSON NOT NULL,
  resumen_json JSON NOT NULL, eliminado TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS anomalias_estados (
  usuario_id INT NOT NULL, anomalia_id VARCHAR(255) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'abierta',
  actualizado_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  visto TINYINT(1) NOT NULL DEFAULT 0, PRIMARY KEY (usuario_id, anomalia_id),
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS notificaciones_estados (
  usuario_id INT NOT NULL, notificacion_id VARCHAR(255) NOT NULL, visto TINYINT(1) NOT NULL DEFAULT 0,
  actualizado_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (usuario_id, notificacion_id),
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
